export const FILE_CATEGORIES = [
  { value: "payment", label: "Payment", icon: "💰" },
  { value: "expense", label: "Expense", icon: "💸" },
  { value: "image", label: "Image", icon: "🖼️" },
  { value: "document", label: "Document", icon: "📄" },
  { value: "contract", label: "Contract", icon: "📋" },
  { value: "invoice", label: "Invoice", icon: "🧾" },
  { value: "other", label: "Other", icon: "📎" },
];

export const FOLDER_COLORS = [
  { value: "blue", label: "Blue", class: "bg-blue-100 dark:bg-blue-900/20 text-blue-700 dark:text-blue-300" },
  { value: "green", label: "Green", class: "bg-green-100 dark:bg-green-900/20 text-green-700 dark:text-green-300" },
  { value: "yellow", label: "Yellow", class: "bg-yellow-100 dark:bg-yellow-900/20 text-yellow-700 dark:text-yellow-300" },
  { value: "red", label: "Red", class: "bg-red-100 dark:bg-red-900/20 text-red-700 dark:text-red-300" },
  { value: "purple", label: "Purple", class: "bg-purple-100 dark:bg-purple-900/20 text-purple-700 dark:text-purple-300" },
  { value: "gray", label: "Gray", class: "bg-gray-100 dark:bg-gray-900/20 text-gray-700 dark:text-gray-300" },
];

export const MESSAGES = {
  pageTitle: "File Management",
  pageDescription: "Organize and manage all operation files",
  newFolder: "New Folder",
  uploadFile: "Upload File",
  allFiles: "All Files",
  download: "Download",
  edit: "Edit",
  delete: "Delete",
  save: "Save",
  cancel: "Cancel",
  folderCreatedSuccess: "Folder created successfully",
  folderUpdatedSuccess: "Folder updated",
  folderDeletedSuccess: "Folder deleted",
  confirmDeleteFolder: "Delete this folder?",
  fileUploadedSuccess: "File uploaded successfully",
  fileUpdatedSuccess: "File updated",
  fileDeletedSuccess: "File deleted",
  confirmDeleteFile: "Delete this file?",
  folderName: "Folder Name",
  folderDescription: "Description",
  folderCategory: "Category",
  folderColor: "Color",
  fileName: "File Name",
  fileDescription: "Description",
  fileCategory: "Category",
  fileFolder: "Folder",
  fileTags: "Tags (comma-separated)",
  noFiles: "No files in this folder",
  selectCategory: "Select category",
  selectColor: "Select color",
  selectFolder: "Select folder",
  uploading: "Uploading...",
};
